platform :ios, '9.0'
use_frameworks!

target 'LoveFreshBeen' do

pod 'SVProgressHUD'
pod 'UMCAnalytics'# 分享
pod 'UMCCommon'# 依赖
pod 'UMCSecurityPlugins'# 依赖
pod 'UMCShare/Social/ReducedQQ'
pod 'UMCShare/Social/ReducedWeChat'
pod 'UMCShare/Social/SMS'
pod 'UMCShare/Social/ReducedSina'
pod 'MJRefresh'
pod 'SDWebImage', '~> 3.8.2'
pod 'MJExtension'

end
